---
abstract: 'CPAN installation management'
author:
  - 'Kang-min Liu  C<< <gugod@gugod.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: cc0
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: perlrocks
name: perlrocks
no_index:
  directory:
    - examples
    - inc
    - share
    - t
recommends:
  B::Hooks::Parser: 0.09
requires:
  CLI::Framework: 0.05
  Exporter::Lite: 0.02
  File::Find: 0
  File::ShareDir: 1.03
  File::Spec: 0
  File::Temp: 0
  HTTP::Tiny: 0.012
  JSON: 2.53
  local::lib: 1.0
  parent: 0.225
resources:
  homepage: http://github.com/gugod/perlrocks/tree
  repository:
    type: git
    url: git://github.com/gugod/perlrocks.git
    web: http://github.com/gugod/perlrocks/tree
version: 0.01
